-- Primary keys, unique keys, check constraints, foreign keys.
alter table public.ad_campaigns add constraint ad_campaigns_pkey PRIMARY KEY (id);
alter table public.advert_events add constraint advert_events_pkey PRIMARY KEY (id);
alter table public.advertisement_requests add constraint advertisement_requests_pkey PRIMARY KEY (id);
alter table public.adverts add constraint adverts_pkey PRIMARY KEY (id);
alter table public.audience_segments add constraint audience_segments_pkey PRIMARY KEY (id);
alter table public.audit_logs add constraint audit_logs_pkey PRIMARY KEY (id);
alter table public.brand_kits add constraint brand_kits_pkey PRIMARY KEY (org_id);
alter table public.buyer_profiles add constraint buyer_profiles_pkey PRIMARY KEY (org_id);
alter table public.campaigns add constraint campaigns_pkey PRIMARY KEY (id);
alter table public.categories add constraint categories_pkey PRIMARY KEY (id);
alter table public.content_items add constraint content_items_pkey PRIMARY KEY (id);
alter table public.countries add constraint countries_pkey PRIMARY KEY (id);
alter table public.currencies add constraint currencies_pkey PRIMARY KEY (code);
alter table public.directory_profiles add constraint directory_profiles_pkey PRIMARY KEY (id);
alter table public.districts add constraint districts_pkey PRIMARY KEY (id);
alter table public.followed_buyers add constraint followed_buyers_pkey PRIMARY KEY (user_id, buyer_org_id);
alter table public.followed_sectors add constraint followed_sectors_pkey PRIMARY KEY (user_id, sector_id);
alter table public.funding_agencies add constraint funding_agencies_pkey PRIMARY KEY (id);
alter table public.influencer_profiles add constraint influencer_profiles_pkey PRIMARY KEY (id);
alter table public.leads add constraint leads_pkey PRIMARY KEY (id);
alter table public.media_assets add constraint media_assets_pkey PRIMARY KEY (id);
alter table public.notification_preferences add constraint notification_preferences_pkey PRIMARY KEY (user_id, org_id, category, channel);
alter table public.notifications add constraint notifications_pkey PRIMARY KEY (id);
alter table public.opportunities add constraint opportunities_pkey PRIMARY KEY (id);
alter table public.opportunity_amendments add constraint opportunity_amendments_pkey PRIMARY KEY (id);
alter table public.opportunity_awards add constraint opportunity_awards_pkey PRIMARY KEY (id);
alter table public.opportunity_categories add constraint opportunity_categories_pkey PRIMARY KEY (opportunity_id, category_id);
alter table public.opportunity_documents add constraint opportunity_documents_pkey PRIMARY KEY (id);
alter table public.opportunity_responses add constraint opportunity_responses_pkey PRIMARY KEY (id);
alter table public.opportunity_statuses add constraint opportunity_statuses_pkey PRIMARY KEY (id);
alter table public.opportunity_types add constraint opportunity_types_pkey PRIMARY KEY (id);
alter table public.organization_members add constraint organization_members_pkey PRIMARY KEY (org_id, user_id);
alter table public.organizations add constraint organizations_pkey PRIMARY KEY (id);
alter table public.pipeline_records add constraint pipeline_records_pkey PRIMARY KEY (id);
alter table public.pipeline_tasks add constraint pipeline_tasks_pkey PRIMARY KEY (id);
alter table public.plan_features add constraint plan_features_pkey PRIMARY KEY (id);
alter table public.plans add constraint plans_pkey PRIMARY KEY (id);
alter table public.procurement_methods add constraint procurement_methods_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.saved_opportunities add constraint saved_opportunities_pkey PRIMARY KEY (user_id, opportunity_id);
alter table public.saved_searches add constraint saved_searches_pkey PRIMARY KEY (id);
alter table public.sectors add constraint sectors_pkey PRIMARY KEY (id);
alter table public.service_request_activities add constraint service_request_activities_pkey PRIMARY KEY (id);
alter table public.service_requests add constraint service_requests_pkey PRIMARY KEY (id);
alter table public.social_connections add constraint social_connections_pkey PRIMARY KEY (id);
alter table public.subscriptions add constraint subscriptions_pkey PRIMARY KEY (id);
alter table public.supplier_profiles add constraint supplier_profiles_pkey PRIMARY KEY (org_id);
alter table public.supplier_sectors add constraint supplier_sectors_pkey PRIMARY KEY (org_id, sector_id);
alter table public.tracking_link_clicks add constraint tracking_link_clicks_pkey PRIMARY KEY (id);
alter table public.tracking_links add constraint tracking_links_pkey PRIMARY KEY (id);
alter table public.verification_requests add constraint verification_requests_pkey PRIMARY KEY (id);
alter table public.adverts add constraint adverts_slug_key UNIQUE (slug);
alter table public.categories add constraint categories_slug_key UNIQUE (slug);
alter table public.countries add constraint countries_code_key UNIQUE (code);
alter table public.opportunities add constraint opportunities_slug_key UNIQUE (slug);
alter table public.opportunity_awards add constraint opportunity_awards_opportunity_id_key UNIQUE (opportunity_id);
alter table public.opportunity_responses add constraint opportunity_responses_opportunity_id_org_id_key UNIQUE (opportunity_id, org_id);
alter table public.opportunity_statuses add constraint opportunity_statuses_code_key UNIQUE (code);
alter table public.opportunity_types add constraint opportunity_types_code_key UNIQUE (code);
alter table public.pipeline_records add constraint pipeline_records_org_id_opportunity_id_key UNIQUE (org_id, opportunity_id);
alter table public.plan_features add constraint plan_features_plan_id_feature_key_key UNIQUE (plan_id, feature_key);
alter table public.plans add constraint plans_code_key UNIQUE (code);
alter table public.procurement_methods add constraint procurement_methods_code_key UNIQUE (code);
alter table public.sectors add constraint sectors_slug_key UNIQUE (slug);
alter table public.tracking_links add constraint tracking_links_short_code_key UNIQUE (short_code);
alter table public.ad_campaigns add constraint ad_campaigns_status_check CHECK ((status = ANY (ARRAY['active'::text, 'paused'::text])));
alter table public.advert_events add constraint advert_events_kind_check CHECK ((kind = ANY (ARRAY['view'::text, 'click'::text])));
alter table public.advertisement_requests add constraint advertisement_requests_category_check CHECK ((category = ANY (ARRAY['business'::text, 'event'::text, 'goods'::text, 'service'::text])));
alter table public.advertisement_requests add constraint advertisement_requests_status_check CHECK ((status = ANY (ARRAY['submitted'::text, 'in_production'::text, 'live'::text, 'completed'::text, 'cancelled'::text])));
alter table public.adverts add constraint adverts_format_check CHECK ((format = ANY (ARRAY['square'::text, 'story'::text, 'landscape'::text, 'banner'::text, 'editorial'::text])));
alter table public.adverts add constraint adverts_status_chk CHECK ((status = ANY (ARRAY['draft'::text, 'live'::text, 'archived'::text])));
alter table public.adverts add constraint adverts_theme_check CHECK ((theme = ANY (ARRAY['dark'::text, 'light'::text])));
alter table public.campaigns add constraint campaigns_status_check CHECK ((status = ANY (ARRAY['Draft'::text, 'Planning'::text, 'Approved'::text, 'Scheduled'::text, 'Active'::text, 'Completed'::text, 'Failed'::text])));
alter table public.content_items add constraint content_items_content_type_check CHECK ((content_type = ANY (ARRAY['Social Post'::text, 'WhatsApp Promo'::text, 'Video Script'::text, 'Radio Brief'::text, 'Email News'::text])));
alter table public.content_items add constraint content_items_status_check CHECK ((status = ANY (ARRAY['Draft'::text, 'Awaiting Review'::text, 'Approved'::text, 'Scheduled'::text, 'Published'::text, 'Failed'::text])));
alter table public.leads add constraint leads_status_check CHECK ((status = ANY (ARRAY['New'::text, 'Contacted'::text, 'Qualified'::text, 'Proposal Sent'::text, 'Converted'::text, 'Lost'::text])));
alter table public.notification_preferences add constraint notification_preferences_channel_check CHECK ((channel = ANY (ARRAY['in_app'::text, 'email'::text])));
alter table public.notification_preferences add constraint notification_preferences_frequency_check CHECK ((frequency = ANY (ARRAY['immediate'::text, 'daily_digest'::text, 'weekly_digest'::text, 'disabled'::text])));
alter table public.notifications add constraint notifications_channel_check CHECK ((channel = ANY (ARRAY['in_app'::text, 'email'::text])));
alter table public.notifications add constraint notifications_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'sent'::text, 'failed'::text, 'read'::text])));
alter table public.opportunities add constraint opportunities_data_confidence_check CHECK ((data_confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])));
alter table public.opportunities add constraint opportunities_source_type_check CHECK ((source_type = ANY (ARRAY['buyer_submission'::text, 'admin_entry'::text, 'document_extraction'::text, 'website_ingestion'::text, 'api_import'::text])));
alter table public.opportunity_amendments add constraint opportunity_amendments_amendment_type_check CHECK ((amendment_type = ANY (ARRAY['content_update'::text, 'deadline_extension'::text, 'cancellation'::text, 'other'::text])));
alter table public.opportunity_responses add constraint opportunity_responses_kind_check CHECK ((kind = ANY (ARRAY['interest'::text, 'intent_to_bid'::text])));
alter table public.opportunity_responses add constraint opportunity_responses_status_check CHECK ((status = ANY (ARRAY['active'::text, 'withdrawn'::text])));
alter table public.organization_members add constraint organization_members_role_check CHECK ((role = ANY (ARRAY['owner'::text, 'admin'::text, 'member'::text])));
alter table public.pipeline_records add constraint pipeline_records_probability_check CHECK (((probability IS NULL) OR ((probability >= 0) AND (probability <= 100))));
alter table public.pipeline_records add constraint pipeline_records_stage_check CHECK ((stage = ANY (ARRAY['saved'::text, 'reviewing'::text, 'interested'::text, 'go'::text, 'no_go'::text, 'preparing'::text, 'submitted'::text, 'won'::text, 'lost'::text, 'withdrawn'::text, 'archived'::text])));
alter table public.profiles add constraint profiles_platform_role_check CHECK ((platform_role = ANY (ARRAY['user'::text, 'researcher'::text, 'admin'::text])));
alter table public.service_requests add constraint service_requests_service_type_check CHECK ((service_type = ANY (ARRAY['document_retrieval'::text, 'tender_clarification'::text, 'eligibility_assessment'::text, 'bid_readiness_review'::text, 'proposal_review'::text, 'company_profile_prep'::text, 'supplier_registration_assistance'::text, 'featured_placement'::text, 'other'::text])));
alter table public.service_requests add constraint service_requests_status_check CHECK ((status = ANY (ARRAY['submitted'::text, 'quoted'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])));
alter table public.social_connections add constraint social_connections_connection_health_check CHECK ((connection_health = ANY (ARRAY['Healthy'::text, 'Warning'::text, 'Disconnected'::text, 'None'::text])));
alter table public.social_connections add constraint social_connections_status_check CHECK ((status = ANY (ARRAY['Connected'::text, 'Sandbox'::text, 'Expired'::text, 'Not Configured'::text])));
alter table public.subscriptions add constraint subscriptions_billing_cycle_check CHECK ((billing_cycle = ANY (ARRAY['monthly'::text, 'annual'::text])));
alter table public.subscriptions add constraint subscriptions_payment_method_check CHECK ((payment_method = ANY (ARRAY['manual_bank_transfer'::text, 'mobile_money'::text, 'card'::text, 'invoice'::text])));
alter table public.subscriptions add constraint subscriptions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'active'::text, 'past_due'::text, 'cancelled'::text, 'expired'::text])));
alter table public.verification_requests add constraint verification_requests_request_type_check CHECK ((request_type = ANY (ARRAY['supplier'::text, 'buyer'::text])));
alter table public.verification_requests add constraint verification_requests_status_check CHECK ((status = ANY (ARRAY['submitted'::text, 'under_review'::text, 'additional_info_required'::text, 'verified'::text, 'rejected'::text, 'suspended'::text, 'expired'::text])));
alter table public.ad_campaigns add constraint ad_campaigns_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.ad_campaigns add constraint ad_campaigns_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.advert_events add constraint advert_events_advert_id_fkey FOREIGN KEY (advert_id) REFERENCES adverts(id) ON DELETE CASCADE;
alter table public.advertisement_requests add constraint advertisement_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.advertisement_requests add constraint advertisement_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id);
alter table public.adverts add constraint adverts_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES ad_campaigns(id) ON DELETE SET NULL;
alter table public.adverts add constraint adverts_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.adverts add constraint adverts_request_id_fkey FOREIGN KEY (request_id) REFERENCES advertisement_requests(id) ON DELETE SET NULL;
alter table public.audience_segments add constraint audience_segments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.audience_segments add constraint audience_segments_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.audit_logs add constraint audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.audit_logs add constraint audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.brand_kits add constraint brand_kits_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.buyer_profiles add constraint buyer_profiles_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.campaigns add constraint campaigns_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.categories add constraint categories_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE SET NULL;
alter table public.content_items add constraint content_items_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL;
alter table public.content_items add constraint content_items_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.countries add constraint countries_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES currencies(code);
alter table public.directory_profiles add constraint directory_profiles_claimed_by_org_id_fkey FOREIGN KEY (claimed_by_org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.directory_profiles add constraint directory_profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.districts add constraint districts_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries(id) ON DELETE CASCADE;
alter table public.followed_buyers add constraint followed_buyers_buyer_org_id_fkey FOREIGN KEY (buyer_org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.followed_buyers add constraint followed_buyers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.followed_sectors add constraint followed_sectors_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE CASCADE;
alter table public.followed_sectors add constraint followed_sectors_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.leads add constraint leads_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.media_assets add constraint media_assets_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.media_assets add constraint media_assets_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id);
alter table public.notification_preferences add constraint notification_preferences_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.notification_preferences add constraint notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.notifications add constraint notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.opportunities add constraint opportunities_buyer_org_id_fkey FOREIGN KEY (buyer_org_id) REFERENCES organizations(id) ON DELETE SET NULL;
alter table public.opportunities add constraint opportunities_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries(id);
alter table public.opportunities add constraint opportunities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.opportunities add constraint opportunities_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES currencies(code);
alter table public.opportunities add constraint opportunities_district_id_fkey FOREIGN KEY (district_id) REFERENCES districts(id);
alter table public.opportunities add constraint opportunities_funding_agency_id_fkey FOREIGN KEY (funding_agency_id) REFERENCES funding_agencies(id);
alter table public.opportunities add constraint opportunities_opportunity_type_id_fkey FOREIGN KEY (opportunity_type_id) REFERENCES opportunity_types(id);
alter table public.opportunities add constraint opportunities_procurement_method_id_fkey FOREIGN KEY (procurement_method_id) REFERENCES procurement_methods(id);
alter table public.opportunities add constraint opportunities_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.opportunities add constraint opportunities_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id);
alter table public.opportunities add constraint opportunities_status_id_fkey FOREIGN KEY (status_id) REFERENCES opportunity_statuses(id);
alter table public.opportunity_amendments add constraint opportunity_amendments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.opportunity_amendments add constraint opportunity_amendments_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.opportunity_awards add constraint opportunity_awards_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.opportunity_awards add constraint opportunity_awards_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES currencies(code);
alter table public.opportunity_awards add constraint opportunity_awards_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.opportunity_categories add constraint opportunity_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE;
alter table public.opportunity_categories add constraint opportunity_categories_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.opportunity_documents add constraint opportunity_documents_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.opportunity_documents add constraint opportunity_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.opportunity_responses add constraint opportunity_responses_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.opportunity_responses add constraint opportunity_responses_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.opportunity_responses add constraint opportunity_responses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.organization_members add constraint organization_members_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.organization_members add constraint organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.organizations add constraint organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.pipeline_records add constraint pipeline_records_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.pipeline_records add constraint pipeline_records_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.pipeline_tasks add constraint pipeline_tasks_pipeline_record_id_fkey FOREIGN KEY (pipeline_record_id) REFERENCES pipeline_records(id) ON DELETE CASCADE;
alter table public.plan_features add constraint plan_features_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES plans(id) ON DELETE CASCADE;
alter table public.plans add constraint plans_currency_code_fkey FOREIGN KEY (currency_code) REFERENCES currencies(code);
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.saved_opportunities add constraint saved_opportunities_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES opportunities(id) ON DELETE CASCADE;
alter table public.saved_opportunities add constraint saved_opportunities_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.saved_searches add constraint saved_searches_district_id_fkey FOREIGN KEY (district_id) REFERENCES districts(id) ON DELETE SET NULL;
alter table public.saved_searches add constraint saved_searches_opportunity_type_id_fkey FOREIGN KEY (opportunity_type_id) REFERENCES opportunity_types(id) ON DELETE SET NULL;
alter table public.saved_searches add constraint saved_searches_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE SET NULL;
alter table public.saved_searches add constraint saved_searches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.service_request_activities add constraint service_request_activities_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.service_request_activities add constraint service_request_activities_request_id_fkey FOREIGN KEY (request_id) REFERENCES service_requests(id) ON DELETE CASCADE;
alter table public.service_requests add constraint service_requests_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.service_requests add constraint service_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.service_requests add constraint service_requests_quote_currency_fkey FOREIGN KEY (quote_currency) REFERENCES currencies(code);
alter table public.service_requests add constraint service_requests_related_opportunity_id_fkey FOREIGN KEY (related_opportunity_id) REFERENCES opportunities(id) ON DELETE SET NULL;
alter table public.service_requests add constraint service_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.social_connections add constraint social_connections_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.subscriptions add constraint subscriptions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.subscriptions add constraint subscriptions_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.subscriptions add constraint subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES plans(id);
alter table public.supplier_profiles add constraint supplier_profiles_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.supplier_sectors add constraint supplier_sectors_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.supplier_sectors add constraint supplier_sectors_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES sectors(id) ON DELETE CASCADE;
alter table public.tracking_link_clicks add constraint tracking_link_clicks_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.tracking_link_clicks add constraint tracking_link_clicks_tracking_link_id_fkey FOREIGN KEY (tracking_link_id) REFERENCES tracking_links(id) ON DELETE CASCADE;
alter table public.tracking_links add constraint tracking_links_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL;
alter table public.tracking_links add constraint tracking_links_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
alter table public.tracking_links add constraint tracking_links_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.verification_requests add constraint verification_requests_org_id_fkey FOREIGN KEY (org_id) REFERENCES organizations(id) ON DELETE CASCADE;
alter table public.verification_requests add constraint verification_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
alter table public.verification_requests add constraint verification_requests_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES auth.users(id) ON DELETE SET NULL;
