import { useEffect, useState } from 'react';
import { AlertTriangle, KeyRound, Loader2, MonitorSmartphone, RefreshCw, ShieldCheck, Trash2 } from 'lucide-react';
import { beginTotpEnrollment, fetchAccountSecurity, observeAccountSession, removeTotpFactor, revokeAccountSession, verifyExistingTotp, verifyTotpFactor, type AccountSecuritySnapshot } from '../lib/accountSecurityApi';
import { supabase } from '../lib/supabaseClient';

export function AccountSecurityPage(){
  const [snapshot,setSnapshot]=useState<AccountSecuritySnapshot|null>(null); const [feedback,setFeedback]=useState(''); const [busy,setBusy]=useState('');
  const [enrollment,setEnrollment]=useState<{id:string;qr:string;secret:string}|null>(null); const [code,setCode]=useState(''); const [stepUp,setStepUp]=useState(false);
  const load=async()=>{setBusy('load');setFeedback('');try{await observeAccountSession();setSnapshot(await fetchAccountSecurity());}catch(x){setFeedback(x instanceof Error?x.message:'Security details could not be loaded.');}finally{setBusy('');}};
  useEffect(()=>{void load();},[]);
  const enroll=async()=>{setBusy('enroll');setFeedback('');try{const data=await beginTotpEnrollment('Manohub authenticator');setEnrollment({id:data.id,qr:data.totp.qr_code,secret:data.totp.secret});}catch(x){setFeedback(x instanceof Error?x.message:'Enrollment could not start.');}finally{setBusy('');}};
  const verifyEnrollment=async()=>{if(!enrollment)return;setBusy('verify');try{await verifyTotpFactor(enrollment.id,code);setEnrollment(null);setCode('');setFeedback('Authenticator protection is now active. Other sessions were signed out.');await load();}catch(x){setFeedback(x instanceof Error?x.message:'Code verification failed.');}finally{setBusy('');}};
  const verifyStepUp=async()=>{setBusy('stepup');try{await verifyExistingTotp(code);setStepUp(false);setCode('');setFeedback('Additional verification completed for this session.');await load();}catch(x){setFeedback(x instanceof Error?x.message:'Code verification failed.');}finally{setBusy('');}};
  const revoke=async(id:string)=>{setBusy(id);try{await revokeAccountSession(id);setFeedback('The selected session was revoked.');await load();}catch(x){setFeedback(x instanceof Error?x.message:'Session could not be revoked.');}finally{setBusy('');}};
  const remove=async()=>{const factors=await supabase.auth.mfa.listFactors();const factor=factors.data?.totp.find(x=>x.status==='verified');if(!factor)return;setBusy('remove');try{await removeTotpFactor(factor.id);setFeedback('Authenticator factor removed.');await load();}catch(x){setFeedback(x instanceof Error?x.message:'Factor could not be removed.');}finally{setBusy('');}};
  if(!snapshot&&busy==='load')return <div role="status" className="grid min-h-64 place-items-center"><Loader2 className="h-7 w-7 animate-spin"/></div>;
  return <div className="space-y-6"><section className="border-2 border-slate-950 bg-slate-950 p-6 text-white"><p className="font-mono text-[9px] font-bold uppercase tracking-[.22em] text-emerald-300">Account protection</p><div className="mt-2 flex flex-col justify-between gap-4 md:flex-row"><div><h2 className="font-display text-3xl font-black !text-white">Account & Session Security</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">Protect sign-ins, inspect active devices and require extra proof for sensitive operations.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 border-2 border-white bg-white px-4 py-2 text-xs font-bold uppercase text-slate-950"><RefreshCw className="h-4 w-4"/>Refresh</button></div></section>
  {feedback&&<p role="status" className="border-2 border-slate-300 bg-white p-3 text-sm">{feedback}</p>}
  <section className="grid gap-4 lg:grid-cols-3"><article className="border-2 border-slate-950 bg-white p-5 lg:col-span-2"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-emerald-600"/><h3 className="font-display text-xl font-black">Multi-factor authentication</h3></div><p className="mt-2 text-sm text-slate-600">{snapshot?.mfaEnabled?'Authenticator protection is enabled.':'Add an authenticator app to protect this account even if the password is stolen.'}</p>
  {!snapshot?.mfaEnabled&&!enrollment&&<button disabled={!!busy} onClick={()=>void enroll()} className="mt-4 bg-slate-950 px-4 py-3 text-xs font-bold uppercase text-white">Set up authenticator</button>}
  {enrollment&&<div className="mt-5 border-2 border-emerald-600 p-4"><img src={enrollment.qr} alt="Authenticator enrollment QR code" className="h-44 w-44"/><p className="mt-3 break-all font-mono text-xs">Manual key: {enrollment.secret}</p><input aria-label="Enrollment verification code" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className="mt-3 w-full border-2 border-slate-300 p-3" placeholder="Six-digit code"/><button disabled={code.length!==6||!!busy} onClick={()=>void verifyEnrollment()} className="mt-3 bg-emerald-700 px-4 py-3 text-xs font-bold uppercase text-white disabled:opacity-50">Verify and enable</button></div>}
  {snapshot?.mfaEnabled&&<div className="mt-4 flex flex-wrap gap-2">{snapshot.assuranceLevel!=='aal2'&&<button onClick={()=>setStepUp(true)} className="bg-emerald-700 px-4 py-3 text-xs font-bold uppercase text-white">Verify sensitive actions</button>}<button disabled={snapshot.assuranceLevel!=='aal2'||!!busy} onClick={()=>void remove()} className="border-2 border-red-700 px-4 py-3 text-xs font-bold uppercase text-red-700 disabled:opacity-40">Remove authenticator</button></div>}
  {stepUp&&<div className="mt-4 border-2 border-amber-500 p-4"><label className="text-xs font-bold uppercase">Authenticator code<input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))} className="mt-2 block w-full border-2 border-slate-300 p-3"/></label><button disabled={code.length!==6||!!busy} onClick={()=>void verifyStepUp()} className="mt-3 bg-slate-950 px-4 py-3 text-xs font-bold uppercase text-white">Complete verification</button></div>}</article>
  <article className="border-2 border-slate-950 bg-emerald-50 p-5"><KeyRound className="h-6 w-6 text-emerald-700"/><h3 className="mt-3 font-display text-xl font-black">Current assurance</h3><p className="mt-2 font-mono text-3xl font-black uppercase">{snapshot?.assuranceLevel??'aal1'}</p><p className="mt-2 text-sm text-slate-600">Sensitive administrative and financial commands require AAL2.</p></article></section>
  <section className="border-2 border-slate-950 bg-white"><div className="border-b-2 border-slate-950 p-5"><div className="flex items-center gap-3"><MonitorSmartphone className="h-6 w-6"/><h3 className="font-display text-xl font-black">Active sessions</h3></div><p className="mt-1 text-sm text-slate-600">Revoke devices you no longer recognize. Your current session cannot be revoked here.</p></div><div className="divide-y-2 divide-slate-200">{snapshot?.sessions.map(s=><article key={s.id} className="flex flex-col justify-between gap-3 p-5 md:flex-row md:items-center"><div><p className="font-bold">{s.current?'This device':s.userAgent}</p><p className="mt-1 text-xs text-slate-500">{s.ipAddress} · Last active {new Date(s.lastSeenAt).toLocaleString()}</p>{s.unusual&&<p className="mt-2 flex items-center gap-1 text-xs font-bold text-amber-700"><AlertTriangle className="h-4 w-4"/>New device or network</p>}</div>{!s.current&&<button disabled={busy===s.id} onClick={()=>void revoke(s.id)} className="flex items-center gap-2 border-2 border-red-700 px-3 py-2 text-xs font-bold uppercase text-red-700"><Trash2 className="h-4 w-4"/>Revoke</button>}</article>)}{snapshot?.sessions.length===0&&<p className="p-5 text-sm text-slate-500">No active sessions were returned.</p>}</div></section>
  <section className="border-2 border-slate-950 bg-white p-5"><h3 className="font-display text-xl font-black">Recent sign-ins</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{snapshot?.recentLogins.map(s=><div key={`${s.id}-${s.createdAt}`} className="border-2 border-slate-200 p-4"><p className="font-bold">{s.userAgent}</p><p className="mt-1 text-xs text-slate-500">{s.ipAddress} · {new Date(s.createdAt).toLocaleString()}</p>{s.unusual&&<p className="mt-2 text-xs font-bold text-amber-700">Unusual sign-in</p>}</div>)}</div></section></div>;
}
