import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Building2, CheckCircle2, FileCheck2, Loader2, Plus, ReceiptText, Users } from 'lucide-react';
import type { Organization } from '../types';
import {
  AgencyApproval, AgencyClient, addAgencyClient, createAgencyApproval, decideAgencyApproval,
  fetchAgencyBilling, fetchAgencyApprovals, fetchAgencyClients, saveAgencyProfile, updateAgencyClient,
  saveAgencyBulkUpload,
} from '../lib/agencyApi';

const PERMISSIONS = ['campaigns_read','campaigns_write','campaigns_approve','billing_read','reports_read','reports_export'];

export function AgencyWorkspacePage({ activeOrg, isPlatformAdmin }: { activeOrg: Organization; isPlatformAdmin: boolean }) {
  const [clients,setClients]=useState<AgencyClient[]>([]);
  const [approvals,setApprovals]=useState<AgencyApproval[]>([]);
  const [billingTotal,setBillingTotal]=useState(0);
  const [loading,setLoading]=useState(true);
  const [feedback,setFeedback]=useState('');
  const [clientOrgId,setClientOrgId]=useState('');
  const [budget,setBudget]=useState('');
  const [approvalClient,setApprovalClient]=useState('');
  const [approvalTitle,setApprovalTitle]=useState('');
  const [approvalDetails,setApprovalDetails]=useState('');
  const [brand,setBrand]=useState({tradingName:activeOrg.name,reportBrandName:activeOrg.name,reportPrimaryColor:'#059669',billingEmail:''});
  const [bulkClient,setBulkClient]=useState('');
  const isAgency = activeOrg.type.trim().toLowerCase().includes('agency');

  const load=async()=>{setLoading(true);try{const c=await fetchAgencyClients(activeOrg.id,isPlatformAdmin);setClients(c);const [a,o]=await Promise.all([fetchAgencyApprovals(c.map(x=>x.id)),fetchAgencyBilling(c.filter(x=>x.status==='active'&&x.permissions.includes('billing_read')).map(x=>x.clientOrgId))]);setApprovals(a);setBillingTotal(o.filter(x=>x.status==='paid').reduce((s,x)=>s+x.totalAmount,0));}catch(e){setFeedback(e instanceof Error?e.message:'Agency workspace could not be loaded.');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[activeOrg.id,isPlatformAdmin]);
  const activeClients=useMemo(()=>clients.filter(c=>c.status==='active'),[clients]);
  const activeAgencyClients=useMemo(()=>activeClients.filter(c=>c.agencyOrgId===activeOrg.id),[activeClients,activeOrg.id]);

  const addClient=async(e:FormEvent)=>{e.preventDefault();try{await addAgencyClient(activeOrg.id,clientOrgId,budget?Number(budget):null);setClientOrgId('');setBudget('');await load();setFeedback('Client invitation created. The client must approve access.');}catch(x){setFeedback(x instanceof Error?x.message:'Client could not be added.');}};
  const requestApproval=async(e:FormEvent)=>{e.preventDefault();try{await createAgencyApproval(approvalClient,approvalTitle,approvalDetails);setApprovalTitle('');setApprovalDetails('');await load();setFeedback('Approval request sent to the client.');}catch(x){setFeedback(x instanceof Error?x.message:'Approval request failed.');}};
  const decide=async(id:string,status:'approved'|'changes_requested')=>{const note=status==='changes_requested'?prompt('What should change?')||'Changes requested.':'';try{await decideAgencyApproval(id,status,note);await load();}catch(x){setFeedback(x instanceof Error?x.message:'Decision could not be saved.');}};
  const saveBrand=async()=>{try{await saveAgencyProfile(activeOrg.id,brand);setFeedback('White-label report settings saved.');}catch(x){setFeedback(x instanceof Error?x.message:'Brand settings could not be saved.');}};
  const uploadCsv=async(file:File|undefined)=>{if(!file||!bulkClient)return;try{const lines=(await file.text()).split(/\r?\n/).filter(Boolean);const headers=lines.shift()?.split(',').map(x=>x.trim())??[];const rows=lines.map(line=>Object.fromEntries(line.split(',').map((value,i)=>[headers[i]||`column_${i+1}`,value.trim()])));await saveAgencyBulkUpload(bulkClient,file.name,rows);setFeedback(`${rows.length} advert briefs uploaded for comparison and review.`);}catch(x){setFeedback(x instanceof Error?x.message:'Bulk upload failed.');}};
  const changeRelationship=async(id:string,patch:Parameters<typeof updateAgencyClient>[1])=>{try{await updateAgencyClient(id,patch);await load();}catch(x){setFeedback(x instanceof Error?x.message:'Agency access could not be updated.');}};

  return <div className="space-y-6 text-left">
    <section className="border border-slate-200 bg-slate-950 p-6 text-white"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-emerald-300">Enhancement 09</p><h2 className="mt-1 font-display text-2xl font-extrabold">Agency Workspace</h2><p className="mt-1 text-sm text-slate-300">Manage clients, delegated permissions, approvals, reports and consolidated billing.</p></section>
    {feedback&&<div className="border border-blue-200 bg-blue-50 p-4 text-sm font-semibold text-blue-800">{feedback}</div>}
    {loading?<div className="flex justify-center p-12 text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading…</div>:<>
      <section className="grid gap-3 sm:grid-cols-4">{[[Building2,'Active clients',activeClients.length],[Users,'All relationships',clients.length],[FileCheck2,'Pending approvals',approvals.filter(a=>a.status==='pending').length],[ReceiptText,'Paid billing',`SLE ${billingTotal.toLocaleString()}`]].map(([Icon,label,value]:any)=><div key={label} className="border bg-white p-5"><Icon className="h-5 w-5 text-emerald-600"/><p className="mt-2 text-xs text-slate-500">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</section>
      <div className="grid gap-6 xl:grid-cols-3">
        <section className="border bg-white xl:col-span-2"><div className="border-b p-5"><h3 className="font-display text-lg font-bold">Clients and permissions</h3></div>{clients.length===0?<p className="p-8 text-sm text-slate-500">No client organisations linked yet.</p>:<div className="divide-y">{clients.map(c=>{const canControl=isPlatformAdmin||c.clientOrgId===activeOrg.id;return <article key={c.id} className="p-5"><div className="flex justify-between gap-3"><div><p className="font-bold">{c.clientName}</p><p className="font-mono text-[10px] text-slate-400">{c.clientOrgId}</p></div><span className="border px-2 py-1 text-[9px] font-bold uppercase">{c.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{PERMISSIONS.map(p=><button key={p} disabled={!canControl||c.status==='ended'} onClick={()=>void changeRelationship(c.id,{permissions:c.permissions.includes(p)?c.permissions.filter(x=>x!==p):[...c.permissions,p]})} className={`border px-2 py-1 text-[10px] disabled:cursor-not-allowed disabled:opacity-60 ${c.permissions.includes(p)?'border-emerald-500 bg-emerald-50 text-emerald-800':'border-slate-200 text-slate-500'}`}>{p.replaceAll('_',' ')}</button>)}</div>{canControl&&c.status!=='ended'&&<div className="mt-3 flex flex-wrap gap-2">{c.status==='pending'&&<button onClick={()=>void changeRelationship(c.id,{status:'active'})} className="bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Approve agency</button>}{c.status==='active'&&<button onClick={()=>void changeRelationship(c.id,{status:'suspended'})} className="border border-amber-500 px-3 py-2 text-xs font-bold text-amber-800">Suspend access</button>}{c.status==='suspended'&&<button onClick={()=>void changeRelationship(c.id,{status:'active'})} className="bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Reactivate</button>}<button onClick={()=>void changeRelationship(c.id,{reportAccessEnabled:!c.reportAccessEnabled})} className="border px-3 py-2 text-xs font-bold">{c.reportAccessEnabled?'Disable':'Enable'} client reports</button><button onClick={()=>void changeRelationship(c.id,{status:'ended'})} className="border border-rose-400 px-3 py-2 text-xs font-bold text-rose-700">End relationship</button></div>}</article>;})}</div>}</section>
        {isAgency&&!isPlatformAdmin?<form onSubmit={addClient} className="h-fit border bg-white p-5"><h3 className="font-display font-bold">Add client</h3><p className="mt-1 text-xs text-slate-500">The client must approve before access becomes active.</p><label className="mt-4 block text-xs font-bold uppercase text-slate-500">Client organisation ID<input required value={clientOrgId} onChange={e=>setClientOrgId(e.target.value)} className="mt-1 w-full border p-3 font-normal normal-case text-slate-900"/></label><label className="mt-3 block text-xs font-bold uppercase text-slate-500">Monthly budget limit<input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)} className="mt-1 w-full border p-3 font-normal text-slate-900"/></label><button className="mt-4 inline-flex items-center gap-2 bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Invite client</button></form>:<aside className="h-fit border bg-slate-50 p-5 text-sm text-slate-600"><h3 className="font-display font-bold text-slate-950">Client-controlled access</h3><p className="mt-2">Only the client organisation can approve, suspend, restore or end agency access and change delegated permissions.</p></aside>}
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        <section className="border bg-white p-5"><h3 className="font-display font-bold">Team approval flow</h3>{isAgency&&!isPlatformAdmin&&<form onSubmit={requestApproval} className="mt-4 grid gap-3"><select required value={approvalClient} onChange={e=>setApprovalClient(e.target.value)} className="border p-3 text-sm"><option value="">Select active client</option>{activeAgencyClients.map(c=><option key={c.id} value={c.id}>{c.clientName}</option>)}</select><input required value={approvalTitle} onChange={e=>setApprovalTitle(e.target.value)} placeholder="Approval title" className="border p-3 text-sm"/><textarea value={approvalDetails} onChange={e=>setApprovalDetails(e.target.value)} placeholder="Campaign, budget or creative details" className="border p-3 text-sm"/><button className="bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Request approval</button></form>}<div className="mt-5 divide-y">{approvals.map(a=>{const relationship=clients.find(c=>c.id===a.agencyClientId);const canDecide=isPlatformAdmin||relationship?.clientOrgId===activeOrg.id;return <div key={a.id} className="py-3"><div className="flex justify-between"><p className="text-sm font-bold">{a.title}</p><span className="text-[9px] font-bold uppercase">{a.status}</span></div>{a.status==='pending'&&canDecide&&<div className="mt-2 flex gap-2"><button onClick={()=>void decide(a.id,'approved')} className="inline-flex items-center gap-1 bg-emerald-600 px-2 py-1 text-xs font-bold text-white"><CheckCircle2 className="h-3 w-3"/>Approve</button><button onClick={()=>void decide(a.id,'changes_requested')} className="border px-2 py-1 text-xs">Request changes</button></div>}</div>;})}</div></section>
        {isAgency&&!isPlatformAdmin?<section className="border bg-white p-5"><h3 className="font-display font-bold">White-labelled reports</h3><div className="mt-4 grid gap-3"><input value={brand.reportBrandName} onChange={e=>setBrand({...brand,reportBrandName:e.target.value})} placeholder="Report brand name" className="border p-3 text-sm"/><input type="color" value={brand.reportPrimaryColor} onChange={e=>setBrand({...brand,reportPrimaryColor:e.target.value})} className="h-12 w-full border p-1"/><input type="email" value={brand.billingEmail} onChange={e=>setBrand({...brand,billingEmail:e.target.value})} placeholder="Consolidated billing email" className="border p-3 text-sm"/><button onClick={()=>void saveBrand()} className="bg-slate-950 px-4 py-2.5 text-sm font-bold text-white">Save report identity</button></div><div className="mt-5 border-l-4 p-4" style={{borderColor:brand.reportPrimaryColor}}><p className="font-bold">{brand.reportBrandName||activeOrg.name}</p><p className="text-xs text-slate-500">Client performance report · verified Hyderra data</p></div></section>:<section className="border bg-white p-5"><h3 className="font-display font-bold">Approval responsibility</h3><p className="mt-2 text-sm text-slate-600">Agency requests remain pending until the client reviews them. Decision evidence is recorded by the database and cannot be edited afterward.</p></section>}
      </div>
      {isAgency&&!isPlatformAdmin&&<section className="border bg-white p-5"><h3 className="font-display font-bold">Bulk advert upload and comparison</h3><p className="mt-1 text-xs text-slate-500">Upload a CSV containing headline, body, format, channel and budget columns. Up to 500 rows enter review; nothing publishes automatically.</p><div className="mt-4 flex flex-col gap-3 sm:flex-row"><select value={bulkClient} onChange={e=>setBulkClient(e.target.value)} className="border p-3 text-sm"><option value="">Select active client</option>{activeAgencyClients.map(c=><option key={c.id} value={c.id}>{c.clientName}</option>)}</select><input type="file" accept=".csv,text/csv" disabled={!bulkClient} onChange={e=>void uploadCsv(e.target.files?.[0])} className="border p-2 text-sm disabled:opacity-50"/></div></section>}
    </>}</div>;
}
