import { useEffect, useState } from 'react';
import { Eye, Loader2, Save } from 'lucide-react';
import { fetchAllLandingContent, LandingContentBlock, updateLandingContent } from '../lib/procurementApi';

export function LandingCmsPage() {
  const [blocks,setBlocks]=useState<LandingContentBlock[]>([]);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState('');
  const [feedback,setFeedback]=useState('');
  useEffect(()=>{fetchAllLandingContent().then(setBlocks).catch(e=>setFeedback(e.message)).finally(()=>setLoading(false));},[]);
  const change=(id:string,patch:Partial<LandingContentBlock>)=>setBlocks(current=>current.map(b=>b.id===id?{...b,...patch}:b));
  const save=async(block:LandingContentBlock)=>{setSaving(block.id);try{await updateLandingContent(block);setFeedback(`${block.title} saved.`);}catch(e){setFeedback(e instanceof Error?e.message:'Content could not be saved.');}finally{setSaving('');}};
  return <div className="space-y-6 text-left">
    <section className="border border-slate-200 bg-slate-950 p-6 text-white"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-orange-300">Public publishing</p><h2 className="mt-1 font-display text-2xl font-extrabold !text-white">Landing Page CMS</h2><p className="mt-1 text-sm text-slate-300">Edit public copy and controlled colour accents without changing Manohub’s theme.</p></section>
    {feedback&&<div role="status" className="border border-blue-200 bg-blue-50 p-4 text-sm font-semibold text-blue-800">{feedback}</div>}
    {loading?<div className="flex justify-center p-12 text-sm text-slate-500"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Loading content…</div>:<div className="grid gap-5">{blocks.map(block=><article key={block.id} className="border bg-white p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[10px] uppercase text-slate-400">{block.section} · {block.blockKey}</p><h3 className="mt-1 font-display text-lg font-bold">{block.title}</h3></div><span className="border px-2 py-1 text-[9px] font-bold uppercase">{block.status}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={block.eyebrow} onChange={e=>change(block.id,{eyebrow:e.target.value})} placeholder="Eyebrow"/><input value={block.title} onChange={e=>change(block.id,{title:e.target.value})} placeholder="Title"/><textarea rows={3} value={block.body} onChange={e=>change(block.id,{body:e.target.value})} placeholder="Body" className="md:col-span-2"/><input value={block.ctaLabel} onChange={e=>change(block.id,{ctaLabel:e.target.value})} placeholder="CTA label"/><input value={block.ctaHref} onChange={e=>change(block.id,{ctaHref:e.target.value})} placeholder="CTA link"/><label className="text-xs font-bold uppercase text-slate-500">Accent<input type="color" value={block.accentColor} onChange={e=>change(block.id,{accentColor:e.target.value})} className="mt-1 h-11 w-full"/></label><label className="text-xs font-bold uppercase text-slate-500">Surface<input type="color" value={block.surfaceColor} onChange={e=>change(block.id,{surfaceColor:e.target.value})} className="mt-1 h-11 w-full"/></label><select value={block.status} onChange={e=>change(block.id,{status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></div><div className="mt-4 flex gap-2"><button onClick={()=>void save(block)} disabled={saving===block.id} className="inline-flex items-center gap-2 bg-slate-950 px-4 py-2.5 text-xs font-bold text-white"><Save className="h-3.5 w-3.5"/>{saving===block.id?'Saving…':'Save block'}</button><a href="/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-slate-950 px-4 py-2.5 text-xs font-bold"><Eye className="h-3.5 w-3.5"/>Preview live page</a></div></article>)}</div>}
  </div>;
}
