import { FormEvent, useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Clock3, CloudCog, DatabaseBackup, HardDrive, LoaderCircle, Plus, RefreshCw, ShieldAlert } from 'lucide-react';
import { BackupRun, declareIncident, fetchBackupRuns, fetchIncidents, fetchRecoveryReadiness, fetchRestoreExercises, IncidentSeverity, IncidentStatus, PlatformIncident, recordRestoreExercise, RecoveryReadiness, RestoreExercise, transitionIncident } from './resilienceApi';

const NEXT_STATUS:Partial<Record<IncidentStatus,IncidentStatus[]>>={
  declared:['investigating','mitigated'],investigating:['mitigated'],mitigated:['monitoring'],
  monitoring:['investigating','resolved'],resolved:['postmortem_complete'],
};
const formatDate=(value:string)=>new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
const severityClass=(value:IncidentSeverity)=>value==='sev1'?'bg-red-600 text-white':value==='sev2'?'bg-orange-400 text-slate-950':value==='sev3'?'bg-amber-200 text-slate-950':'bg-sky-100 text-sky-900';

export function AdminResilienceWorkspace(){
  const[incidents,setIncidents]=useState<PlatformIncident[]>([]);const[exercises,setExercises]=useState<RestoreExercise[]>([]);const[backups,setBackups]=useState<BackupRun[]>([]);const[readiness,setReadiness]=useState<RecoveryReadiness|null>(null);
  const[loading,setLoading]=useState(true);const[feedback,setFeedback]=useState('');const[showIncident,setShowIncident]=useState(false);const[showExercise,setShowExercise]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setFeedback('');try{const[i,e,b,r]=await Promise.all([fetchIncidents(),fetchRestoreExercises(),fetchBackupRuns(),fetchRecoveryReadiness()]);setIncidents(i);setExercises(e);setBackups(b);setReadiness(r)}catch(error){setFeedback(error instanceof Error?error.message:'Could not load resilience records.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const advance=async(item:PlatformIncident,status:IncidentStatus)=>{const note=window.prompt(`Move ${item.reference} to ${status.replace('_',' ')}. Add an operational note:`);if(!note)return;try{await transitionIncident(item.id,status,note);setFeedback(`${item.reference} moved to ${status.replace('_',' ')}.`);await load()}catch(error){setFeedback(error instanceof Error?error.message:'Incident transition failed.')}};
  const active=incidents.filter(i=>!['resolved','postmortem_complete'].includes(i.status));
  const restorePasses=exercises.filter(e=>e.status!=='failed').length;
  return <div className="space-y-6 text-left">
    <section className="border-2 border-slate-950 bg-slate-950 p-6 text-white"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div>
      <p className="font-mono text-[9px] font-bold uppercase tracking-[.22em] text-emerald-300">Operational resilience</p><h2 className="mt-2 font-display text-3xl font-extrabold !text-white">Reliability & Recovery</h2>
      <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Command incidents, enforce recovery objectives and retain evidence that backups can actually be restored.</p></div>
      <div className="flex flex-wrap gap-2"><button onClick={()=>setShowIncident(v=>!v)} className="inline-flex items-center gap-2 border-2 border-white bg-red-500 px-4 py-2 font-mono text-[9px] font-bold uppercase"><ShieldAlert className="h-4 w-4"/>Declare incident</button>
      <button onClick={()=>setShowExercise(v=>!v)} className="inline-flex items-center gap-2 border-2 border-white bg-white px-4 py-2 font-mono text-[9px] font-bold uppercase text-slate-950"><DatabaseBackup className="h-4 w-4"/>Record restore test</button></div></div></section>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[
      ['Active incidents',active.length,AlertTriangle,'bg-red-400'],['SEV1 / SEV2',active.filter(i=>['sev1','sev2'].includes(i.severity)).length,ShieldAlert,'bg-orange-400'],
      ['Restore exercises',exercises.length,DatabaseBackup,'bg-violet-400'],['Passing evidence',restorePasses,CheckCircle2,'bg-emerald-400'],
    ].map(([label,value,Icon,accent]:any)=><div key={label} className="relative border-2 border-slate-950 bg-white p-5"><span className={`absolute inset-x-0 top-0 h-1.5 ${accent}`}/><div className="flex justify-between"><span className="font-mono text-[9px] font-bold uppercase text-slate-500">{label}</span><Icon className="h-4 w-4"/></div><span className="mt-3 block font-display text-3xl font-extrabold">{value}</span></div>)}</section>
    {showIncident&&<IncidentForm onDone={async()=>{setShowIncident(false);await load()}}/>}
    {showExercise&&<ExerciseForm onDone={async()=>{setShowExercise(false);await load()}}/>}
    {feedback&&<div className="border-2 border-slate-950 bg-amber-50 p-3 text-xs">{feedback}</div>}
    <section className="border-2 border-slate-950 bg-white"><header className="border-b-2 border-slate-950 p-4"><p className="font-mono text-[9px] font-bold uppercase text-blue-700">Backup verification</p><h3 className="font-display text-xl font-extrabold">Disaster-recovery readiness</h3></header>
      <div className="grid gap-3 p-4 md:grid-cols-4"><RecoveryMetric label="Database" value={readiness?.databaseMethod.replaceAll('_',' ')??'Not configured'} icon={DatabaseBackup}/><RecoveryMetric label="Storage" value={readiness?.storageMethod.replaceAll('_',' ')??'Not configured'} icon={HardDrive}/><RecoveryMetric label="Target RPO / RTO" value={readiness?`${readiness.targetRpoMinutes}m / ${readiness.targetRtoMinutes}m`:'—'} icon={Clock3}/><RecoveryMetric label="PITR" value={readiness?.pitrStatus.replaceAll('_',' ')??'Unavailable'} icon={CloudCog}/></div>
      {readiness?.backupOverdue&&<p className="mx-4 mb-4 border-l-4 border-red-600 bg-red-50 p-3 text-xs font-bold text-red-900">Backup evidence is missing or older than the configured RPO. Investigate the protected backup workflow.</p>}
      <div className="divide-y-2 divide-slate-200 border-t-2 border-slate-950">{backups.length===0?<p className="p-6 text-center text-sm text-slate-500">No automated backup evidence has been recorded. The workflow must not be treated as active until protected off-site credentials are configured.</p>:backups.map(run=><article key={run.id} className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_160px_180px]"><div><div className="flex flex-wrap gap-2"><span className="font-mono text-[9px] font-bold">{run.runReference}</span><span className={`px-2 py-0.5 font-mono text-[8px] font-bold uppercase ${run.status==='failed'?'bg-red-100 text-red-800':run.status==='verified'?'bg-violet-100 text-violet-800':'bg-emerald-100 text-emerald-800'}`}>{run.status}</span></div><p className="mt-2 text-xs">{run.backupKind} · {run.triggerSource}{run.objectCount==null?'':` · ${run.objectCount.toLocaleString()} objects`}</p>{run.failureSummary&&<p className="mt-2 text-xs text-red-700">{run.failureSummary}</p>}</div><div className="font-mono text-[9px]">Backup point<br/><strong>{formatDate(run.backupPointAt)}</strong></div><div className="font-mono text-[9px]">Integrity manifest<br/><strong>{run.manifestSha256?.slice(0,12)??'not available'}</strong>{run.workflowRunUrl&&<><br/><a className="text-blue-700 underline" href={run.workflowRunUrl} target="_blank" rel="noreferrer">Workflow evidence</a></>}</div></article>)}</div>
    </section>
    <section className="border-2 border-slate-950 bg-white"><header className="flex items-center justify-between border-b-2 border-slate-950 p-4"><div><p className="font-mono text-[9px] font-bold uppercase text-violet-700">Incident command</p><h3 className="font-display text-xl font-extrabold">Incident register</h3></div><button onClick={()=>void load()} className="border-2 border-slate-950 p-2" aria-label="Refresh resilience records"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></header>
      {loading?<div className="grid min-h-40 place-items-center"><LoaderCircle className="animate-spin"/></div>:incidents.length===0?<div className="grid min-h-40 place-items-center text-sm text-slate-500">No incidents have been declared.</div>:<div className="divide-y-2 divide-slate-200">{incidents.map(item=><article key={item.id} className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1fr)_180px_240px]"><div><div className="flex flex-wrap items-center gap-2"><span className={`px-2 py-1 font-mono text-[8px] font-bold uppercase ${severityClass(item.severity)}`}>{item.severity}</span><span className="font-mono text-[9px] font-bold">{item.reference}</span><span className="border px-2 py-1 font-mono text-[8px] uppercase">{item.status.replace('_',' ')}</span></div><h4 className="mt-2 font-display font-extrabold">{item.title}</h4><p className="mt-1 text-xs text-slate-600">{item.affectedService} · {item.summary}</p>{item.customerImpact&&<p className="mt-2 border-l-4 border-red-500 bg-red-50 p-2 text-xs"><strong>Impact:</strong> {item.customerImpact}</p>}</div><dl className="font-mono text-[9px] text-slate-600"><dt>RPO / RTO targets</dt><dd className="font-bold">{item.rpoMinutes}m / {item.rtoMinutes}m</dd><dt className="mt-2">Declared</dt><dd>{formatDate(item.declaredAt)}</dd></dl><div className="flex flex-wrap justify-end gap-2">{(NEXT_STATUS[item.status]??[]).map(status=><button key={status} onClick={()=>void advance(item,status)} className="h-fit border-2 border-slate-950 px-3 py-2 font-mono text-[8px] font-bold uppercase">{status.replace('_',' ')}</button>)}</div></article>)}</div>}</section>
    <section className="border-2 border-slate-950 bg-white"><header className="border-b-2 border-slate-950 p-4"><p className="font-mono text-[9px] font-bold uppercase text-emerald-700">Recovery assurance</p><h3 className="font-display text-xl font-extrabold">Restore exercise evidence</h3></header>
      {exercises.length===0?<div className="grid min-h-32 place-items-center p-6 text-center text-sm text-slate-500">No restore exercise recorded yet. A backup is not proven until a restoration succeeds.</div>:<div className="divide-y-2 divide-slate-200">{exercises.map(item=><article key={item.id} className="grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_180px_180px]"><div><div className="flex gap-2"><span className="font-mono text-[9px] font-bold uppercase">{item.exerciseType.replaceAll('_',' ')}</span><span className={`px-2 py-0.5 font-mono text-[8px] font-bold uppercase ${item.status==='failed'?'bg-red-100 text-red-800':'bg-emerald-100 text-emerald-800'}`}>{item.status.replaceAll('_',' ')}</span></div><p className="mt-2 text-xs">{item.findings}</p><p className="mt-1 font-mono text-[9px] text-violet-700">{item.evidenceReference}</p></div><div className="font-mono text-[9px]"><Clock3 className="mb-1 h-4 w-4"/><strong>Achieved RPO / RTO</strong><br/>{item.achievedRpoMinutes}m / {item.achievedRtoMinutes}m</div><div className="font-mono text-[9px]">Completed<br/><strong>{formatDate(item.completedAt)}</strong><br/>{item.environment.replace('_',' ')}</div></article>)}</div>}</section>
  </div>
}

function RecoveryMetric({label,value,icon:Icon}:{label:string;value:string;icon:typeof DatabaseBackup}){return <div className="border border-slate-300 p-3"><div className="flex items-center justify-between"><span className="font-mono text-[8px] font-bold uppercase text-slate-500">{label}</span><Icon className="h-4 w-4"/></div><strong className="mt-2 block text-sm capitalize">{value}</strong></div>}

function IncidentForm({onDone}:{onDone:()=>Promise<void>}){const[busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await declareIncident({title:String(f.get('title')),summary:String(f.get('summary')),affectedService:String(f.get('service')),severity:String(f.get('severity'))as IncidentSeverity,customerImpact:String(f.get('impact')),rpoMinutes:Number(f.get('rpo')),rtoMinutes:Number(f.get('rto'))});await onDone()}finally{setBusy(false)}};return <form onSubmit={submit} className="grid gap-3 border-2 border-red-700 bg-red-50 p-5 md:grid-cols-2"><h3 className="font-display text-xl font-extrabold md:col-span-2">Declare an incident</h3><input required minLength={5} name="title" placeholder="Incident title" className="border-2 border-slate-950 p-3"/><input required name="service" placeholder="Affected service" className="border-2 border-slate-950 p-3"/><select name="severity" className="border-2 border-slate-950 p-3"><option value="sev1">SEV1 — critical</option><option value="sev2">SEV2 — major</option><option value="sev3">SEV3 — moderate</option><option value="sev4">SEV4 — minor</option></select><input name="impact" placeholder="Customer impact" className="border-2 border-slate-950 p-3"/><textarea required minLength={10} name="summary" placeholder="What happened?" className="border-2 border-slate-950 p-3 md:col-span-2"/><label className="text-xs font-bold">RPO target (minutes)<input type="number" min="0" name="rpo" defaultValue="1440" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><label className="text-xs font-bold">RTO target (minutes)<input type="number" min="1" name="rto" defaultValue="240" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><button disabled={busy} className="border-2 border-slate-950 bg-slate-950 p-3 font-mono text-[9px] font-bold uppercase text-white md:col-span-2"><Plus className="mr-2 inline h-4 w-4"/>Declare incident</button></form>}
function ExerciseForm({onDone}:{onDone:()=>Promise<void>}){const[busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await recordRestoreExercise({exerciseType:String(f.get('type')),environment:String(f.get('environment')),status:String(f.get('status')),backupPointAt:new Date(String(f.get('backupPoint'))).toISOString(),startedAt:new Date(String(f.get('started'))).toISOString(),completedAt:new Date(String(f.get('completed'))).toISOString(),achievedRpoMinutes:Number(f.get('rpo')),achievedRtoMinutes:Number(f.get('rto')),evidenceReference:String(f.get('evidence')),findings:String(f.get('findings'))});await onDone()}finally{setBusy(false)}};return <form onSubmit={submit} className="grid gap-3 border-2 border-violet-700 bg-violet-50 p-5 md:grid-cols-2"><h3 className="font-display text-xl font-extrabold md:col-span-2">Record restore exercise</h3><select name="type" className="border-2 border-slate-950 p-3"><option value="database">Database</option><option value="storage">Storage objects</option><option value="cloudflare_configuration">Cloudflare configuration</option><option value="dns">DNS</option><option value="full_service">Full service</option></select><select name="environment" className="border-2 border-slate-950 p-3"><option value="recovery_sandbox">Recovery sandbox</option><option value="staging">Staging</option></select><select name="status" className="border-2 border-slate-950 p-3"><option value="passed">Passed</option><option value="passed_with_actions">Passed with actions</option><option value="failed">Failed</option></select><input required name="evidence" placeholder="Evidence URL, ticket or report reference" className="border-2 border-slate-950 p-3"/><label className="text-xs font-bold">Backup point<input required type="datetime-local" name="backupPoint" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><label className="text-xs font-bold">Started<input required type="datetime-local" name="started" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><label className="text-xs font-bold">Completed<input required type="datetime-local" name="completed" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><label className="text-xs font-bold">Achieved RPO (minutes)<input required type="number" min="0" name="rpo" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><label className="text-xs font-bold">Achieved RTO (minutes)<input required type="number" min="0" name="rto" className="mt-1 w-full border-2 border-slate-950 p-3"/></label><textarea required minLength={3} name="findings" placeholder="Findings and follow-up actions" className="border-2 border-slate-950 p-3"/><button disabled={busy} className="border-2 border-slate-950 bg-slate-950 p-3 font-mono text-[9px] font-bold uppercase text-white md:col-span-2"><DatabaseBackup className="mr-2 inline h-4 w-4"/>Save exercise evidence</button></form>}
