import { useCallback, useEffect, useState } from 'react';
import { Building2, LoaderCircle, RefreshCw, RotateCcw, Search, ShieldAlert, XCircle } from 'lucide-react';
import { AdminOrganizationRecord, decideOrganizationRecovery, fetchAdminOrganizations, OrganizationLifecycleStatus, transitionOrganization } from './organizationAdminApi';

const FILTERS:Array<{value:OrganizationLifecycleStatus|null;label:string}>=[
  {value:null,label:'All'},{value:'recovery_pending',label:'Recovery pending'},{value:'suspended',label:'Suspended'},
  {value:'closed',label:'Closed'},{value:'active',label:'Active'},
];
export function AdminOrganizationLifecycleWorkspace(){
  const[items,setItems]=useState<AdminOrganizationRecord[]>([]);const[filter,setFilter]=useState<OrganizationLifecycleStatus|null>(null);
  const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[feedback,setFeedback]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{setItems(await fetchAdminOrganizations(filter,search));}catch(e){setFeedback(e instanceof Error?e.message:'Could not load organizations.');}finally{setLoading(false)}},[filter,search]);
  useEffect(()=>{void load()},[load]);
  const act=async(item:AdminOrganizationRecord,action:'suspend'|'reactivate'|'close')=>{
    const reason=window.prompt(`${action} ${item.name}: provide a reason (minimum 10 characters).`);if(!reason)return;
    setBusy(item.id);setFeedback('');try{await transitionOrganization(item.id,action,reason);setFeedback(`${item.name} is now ${action==='reactivate'?'active':action==='close'?'closed':'suspended'}.`);await load();}catch(e){setFeedback(e instanceof Error?e.message:'Organization action failed.');}finally{setBusy('')}
  };
  const decide=async(item:AdminOrganizationRecord,approve:boolean)=>{if(!item.recoveryRequestId)return;const note=window.prompt(`${approve?'Approve':'Reject'} recovery for ${item.name}: add a decision note.`);if(!note)return;
    setBusy(item.id);try{await decideOrganizationRecovery(item.recoveryRequestId,approve,note);setFeedback(`Recovery ${approve?'approved':'rejected'} for ${item.name}.`);await load();}catch(e){setFeedback(e instanceof Error?e.message:'Recovery decision failed.');}finally{setBusy('')}};
  return <div className="space-y-6 text-left">
    <section className="border-2 border-slate-950 bg-slate-950 p-6 text-white"><p className="font-mono text-[9px] font-bold uppercase tracking-[.22em] text-violet-300">Customer governance</p><h2 className="mt-2 font-display text-3xl font-extrabold !text-white">Organizations & Recovery</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">Suspend access, review recovery requests and manage recoverable organization closure from one controlled workspace.</p></section>
    <section className="border-2 border-slate-950 bg-white"><div className="flex flex-col gap-3 border-b-2 border-slate-950 p-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{FILTERS.map(f=><button key={f.label} onClick={()=>setFilter(f.value)} className={`border-2 px-3 py-2 font-mono text-[9px] font-bold uppercase ${filter===f.value?'border-slate-950 bg-slate-950 text-white':'border-slate-300 text-slate-600'}`}>{f.label}</button>)}</div><div className="flex gap-2"><label className="flex items-center gap-2 border-2 border-slate-300 px-3"><Search className="h-4 w-4"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search organizations" className="border-0 p-2 text-xs outline-none"/></label><button onClick={()=>void load()} className="border-2 border-slate-950 p-2"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div></div>
      {feedback&&<div className="border-b-2 border-slate-950 bg-amber-50 px-4 py-3 text-xs text-slate-800">{feedback}</div>}
      {loading?<div className="grid min-h-48 place-items-center"><LoaderCircle className="h-6 w-6 animate-spin"/></div>:items.length===0?<div className="grid min-h-48 place-items-center text-sm text-slate-500">No matching organizations.</div>:<div className="divide-y-2 divide-slate-200">{items.map(item=><article key={item.id} className="grid gap-4 p-4 lg:grid-cols-[minmax(0,1fr)_180px_260px] lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><Building2 className="h-4 w-4 text-emerald-600"/><h3 className="font-display font-extrabold">{item.name}</h3><span className="border px-2 py-0.5 font-mono text-[8px] font-bold uppercase">{item.status.replace('_',' ')}</span></div><p className="mt-1 text-xs text-slate-500">{item.type} · {item.memberCount} member{item.memberCount===1?'':'s'} · {item.activePlan??'No active plan'}</p>{item.statusReason&&<p className="mt-2 border-l-4 border-amber-400 bg-amber-50 p-2 text-xs">{item.statusReason}</p>}{item.recoveryReason&&<p className="mt-2 border-l-4 border-violet-500 bg-violet-50 p-2 text-xs"><strong>Recovery:</strong> {item.recoveryReason}</p>}</div><div className="font-mono text-[9px] text-slate-500">Updated<br/>{new Date(item.updatedAt).toLocaleString('en-GB')}</div><div className="flex flex-wrap justify-end gap-2">{item.status==='recovery_pending'&&<><button onClick={()=>void decide(item,true)} disabled={busy===item.id} className="border-2 border-emerald-700 bg-emerald-50 px-3 py-2 text-[9px] font-bold uppercase text-emerald-800"><RotateCcw className="mr-1 inline h-3.5 w-3.5"/>Approve recovery</button><button onClick={()=>void decide(item,false)} disabled={busy===item.id} className="border-2 border-red-700 px-3 py-2 text-[9px] font-bold uppercase text-red-700">Reject</button></>}{item.status==='active'&&<><button onClick={()=>void act(item,'suspend')} disabled={busy===item.id} className="border-2 border-amber-700 px-3 py-2 text-[9px] font-bold uppercase text-amber-800"><ShieldAlert className="mr-1 inline h-3.5 w-3.5"/>Suspend</button><button onClick={()=>void act(item,'close')} disabled={busy===item.id} className="border-2 border-red-700 px-3 py-2 text-[9px] font-bold uppercase text-red-700"><XCircle className="mr-1 inline h-3.5 w-3.5"/>Close</button></>}{['suspended','closed'].includes(item.status)&&<button onClick={()=>void act(item,'reactivate')} disabled={busy===item.id} className="border-2 border-emerald-700 px-3 py-2 text-[9px] font-bold uppercase text-emerald-800">Reactivate</button>}</div></article>)}</div>}
    </section>
  </div>
}
